### ISSUE TITLE
V1 - Wrong Event Docs, Track is identifier instead of wavelink.Track

### ISSUE THREAD

**Issue by Luc1412** [PythonistaGuild/Wavelink#106]
1. The event Docs doesn't mention the provided Player for on_wavelink_track_start, on_wavelink_track_end, on_wavelink_track_exception and on_wavelink_track_stuck
2. The docs (at least in 0.9) mention that a wavelink.Track is provided with these events even trough the identifier is just provided

**Comment by EvieePy** [comment]
This will be fixed shortly for  [Branch 1.0](https://github.com/PythonistaGuild/Wavelink/tree/1.0)

**Comment by EvieePy** [comment]
This is for an outdated version of Wavelink. Thanks!
