### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by RAINGM1** [PythonistaGuild/Wavelink#108]
Hello, can we get filters like on [distube.js](https://distube.js.org/#/docs/DisTube/v2/typedef/Filter) or how can i do this?

**Comment by EvieePy** [comment]
Filters will be released in the pre release in the next few days.

**Comment by RAINGM1** [comment]
Thx for quick response

**Comment by RAINGM1** [comment]
Can i ask about filters, when date release and whats functions will be include?

**Comment by EvieePy** [comment]
Filters are currently being worked on for the pre release  [Branch 1.0](https://github.com/PythonistaGuild/Wavelink/tree/1.0) which now supersedes master. You should expect them to release in a couple of days.

**Comment by EvieePy** [comment]
#105
