### ISSUE TITLE
discord py 2.0

### ISSUE THREAD

**Issue by helish88** [PythonistaGuild/Wavelink#118]
After i installed dpy 2.0 music doesn't works
![image](https://user-images.githubusercontent.com/52331802/128668057-5869573c-7ca8-42f7-893a-94620bca92fa.png)
I have last Wavelink version and Lavalink.jar last version

**Comment by Sk1pzz** [comment]
Same issue here. No errors, nothing.

**Comment by Asherlam** [comment]
Same issue, im using wavelink 9.10 and discord.py 2.0

**Comment by helish88** [comment]
pip install -U wavelink --pre
and it works

**Comment by tooty-1135** [comment]
try this
https://github.com/Cog-Creators/Lavalink-Jars/releases

**Comment by chillymosh** [comment]
Lavalink 3.7.5 and Wavelink 2.3 is the latest and recommended versions
