### ISSUE TITLE
How can I make the repeat command

### ISSUE THREAD

**Issue by z3r0xxx** [PythonistaGuild/Wavelink#121]
I want to make a command that allows you to loop the current track/queue. How can I implement this?

**Comment by DWAA1660** [comment]
this isnt support u can look at glowsticks vid if you want tho

**Comment by IAmTomahawkx** [comment]
YouTube videos are discouraged. Please use the discord support server linked in the readme, along with the documentation for such. Also please don't necrobump year old issues
