### ISSUE TITLE
Local audio files

### ISSUE THREAD

**Issue by RAlNGM** [PythonistaGuild/Wavelink#124]
Hey, how can i make playing local audio files?

**Comment by Zekann** [comment]
For me i'm use wavelink.PartialTrack(query=path, cls=wavelink.LocalTrack)

And work for me

**Comment by ashroyxi** [comment]
what is the path. like where the bot codes are, or where the lavalink files are

**Comment by ashroyxi** [comment]
for me it says `IndexError: list index out of range`
can you like give me an example code?
mine was
```
node = wavelink.NodePool.get_node()
player = node.get_player(interaction.guild)

await interaction.user.voice.channel.connect(cls=wavelink.Player)

search = wavelink.PartialTrack(query="./cogs/welcome.mp3", cls=wavelink.LocalTrack)

vc : wavelink.Player = interaction.guild.voice_client

await vc.play(search)
```

**Comment by ashroyxi** [comment]
@RAlNGM why did you close this? what is the solution?
