### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by Jaguar000212** [PythonistaGuild/Wavelink#130]
The bot connects to vc, sends embed and do everything in Music cog but no sound! Even the play commands queues the song and we can check the quene! please help me asap

Using discord.py (Master)
          Python 3.8
          Wavelink 0.9.4

EDIT : There is no error too

**Comment by IAmTomahawkx** [comment]
This is not an issue with wavelink. For support, please visit the wavelink [server](https://discord.gg/RAKc3HF) listed in the readme
