### ISSUE TITLE
module 'wavelink' has no attribute 'client'

### ISSUE THREAD

**Issue by sanjaysanooj22** [PythonistaGuild/Wavelink#146]
Traceback (most recent call last):
  File "/Users/admin/Desktop/Cogs/music1.py", line 272, in <module>
    bot = Bot()
  File "/Users/admin/Desktop/Cogs/music1.py", line 22, in __init__
    self.add_cog(Music(self))
  File "/Users/admin/Desktop/Cogs/music1.py", line 69, in __init__
    self.bot.wavelink = wavelink.Client(bot=self.bot)
AttributeError: module 'wavelink' has no attribute 'Client'

**Comment by chillymosh** [comment]
This is not an issue or a bug. Wavelink 1.x no longer has Client.
Please check the docs https://wavelink.readthedocs.io/en/latest/recipes.html

**Comment by sanjaysanooj22** [comment]
So what should I do

**Comment by chillymosh** [comment]
Read the docs or join the discord. You are using an outdated tutorial / example for wavelink 0.9.
d.py 2.0 and forks based off that require wavelink 1.x which does not have Client.

**Comment by chillymosh** [comment]
This is not an issue, simply using an outdated version.
