### ISSUE TITLE
Can't find Equalizer support in this rewrite

### ISSUE THREAD

**Issue by pritam20ps05** [PythonistaGuild/Wavelink#148]
Are we getting any Equalizer support any soon. If not then how can we do that. I want to add both Equalizer and Spotify support.

**Comment by chillymosh** [comment]
Equalizer / filters are in the filters branch. They are yet to be merged into the Master but will be as soon as the documentation is written. Spotify support already exists in Master.

**Comment by Axelancerr** [comment]
#160 will implement filters.

**Comment by Axelancerr** [comment]
Closed by #160
