### ISSUE TITLE
Node.__repr__() raises IndexError when host is not an IP

### ISSUE THREAD

**Issue by gamescom15** [PythonistaGuild/Wavelink#15]
Steps to reproduce:
Call `.initiate_node()` on a `wavelink.Client` object with the requred parameters, and `host="lavalink"` (or any str with no `.`)

Later in the function,  `__repr__()` is called on a `Node`: https://github.com/EvieePy/Wavelink/blob/master/wavelink/client.py#L304
-> https://github.com/EvieePy/Wavelink/blob/master/wavelink/node.py#L69

This `__repr__()` tries to splilt by `.` and then access `[0]` and `[1]`
However, when the hostname includes no `.`s (e.g. for local container hostnames in Docker), `IndexError` is raised on `[1]`.

**Comment by EvieePy** [comment]
Fixed as host was removed from repr. Thanks
