### ISSUE TITLE
cant search for youtube playlist

### ISSUE THREAD

**Issue by tunwit** [PythonistaGuild/Wavelink#154]
I try to use wavelink.YouTubePlaylist to search for youtubeplaylist and I get error

**code**
`@commands.command(aliases=['P', 'PLAY', 'Play','p'])
 async def play(self,ctx: commands.Context, *, search:wavelink.YouTubePlaylist):
      print(search)`

**error**
`Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Python3.10\lib\site-packages\discord\ext\commands\core.py", line 456, in _actual_conversion
    ret = await method(ctx, argument)
  File "C:\Python3.10\lib\site-packages\wavelink\tracks.py", line 218, in convert
    return results[0]
TypeError: 'YouTubePlaylist' object is not subscriptable`

Did i miss something?

and also sorry for my bad English

**Comment by tobycm** [comment]
for me, I don't put the converter in the function arg, instead I do a try except to search in YouTubeTrack and if fails search in YouTubePlaylist

**Comment by chillymosh** [comment]
This was fixed in commit 31e29db
