### ISSUE TITLE
Player.is_playing always returns False after track replace

### ISSUE THREAD

**Issue by wladbelsky** [PythonistaGuild/Wavelink#156]
Was broken in this commit: https://github.com/PythonistaGuild/Wavelink/commit/f126755662cdf17199b7814dbe4abcb5f038966b
After first track has been replaced with `Player.play(track)`, track_end event triggered after `Player.play` done. So, after first track replaced, `Player._source` is always None and `Player.is_playing()` always returns False.

Consider changing code from commit above to something like this:
```python
if event == 'track_end' and payload.get('reason') == 'FINISHED':
    player._source = None
```

**Comment by TechFun4** [comment]
I can confirm that this is an issue.

**Comment by TechFun4** [comment]
```py
if event == 'track_end' and payload.get('reason') != 'REPLACED':
    player._source = None
```
would also do.

**Comment by hackermub** [comment]
> Any progress on this getting fixed yet? It completely breaks any sort of skipping logic.

Doesn't see any change in the master branch.. Manually modified it to fix it.

**Comment by zeph-yrus9** [comment]
could it be that track end event is triggered late i.e after the player start playing next track!

**Comment by timelessnesses** [comment]
i don't think your fix works on my machine? (its not permanent)  
still getting track replaced though there's check if its playing

**Comment by 26939095** [comment]
bump repair plz m(_ _)m

**Comment by holy-crusader-py** [comment]
> bump repair plz m(_ _)m

I've created a [fork](https://github.com/Ether-DiscordBot/Ether-Wavelink) for my bot that solve the issue while waiting for a fix.
If you want to use it:
```
requirements.txt

# wavelink==1.3.3
git+https://github.com/Ether-DiscordBot/Ether-Wavelink.git
```
