### ISSUE TITLE
queue error please help

### ISSUE THREAD

**Issue by slefgameRz** [PythonistaGuild/Wavelink#158]
@bot.event
async def on_wavelink_track_end(player: wavelink.Player, track: wavelink.Track, reason):
        ctx = player.ctx
        vc: player = ctx.voice_client
        if vc.loop:
            return await vc.play(track)
        next_song = vc.queue.get()
        await vc.play(next_song)
        await ctx.send(f"Now playing {next_song.title}")

-   File "/home/container/discord-bot/main.py", line 118, in on_wavelink_track_end
    next_song = vc.queue.get()
  File "/home/container/.local/lib/python3.10/site-packages/wavelink/queue.py", line 212, in get
    raise QueueEmpty("No items in the queue.")
wavelink.errors.QueueEmpty: No items in the queue.

**Comment by chillymosh** [comment]
How are you adding the tracks to the queue?

**Comment by slefgameRz** [comment]
> How are you adding the tracks to the queue?

I don't know how it is added, I don't know much about this aspect.
Can you please tell me how to add it?

**Comment by chillymosh** [comment]
This is within a cog, simply remove the `self` if you are not running this in a cog.
I would also recommend joining the discord server for further support.
```
    @commands.command()
    async def play(self, ctx: commands.Context, *, search: wavelink.YouTubeTrack):
        """Play a song with the given search query.

        If not connected, connect to our voice channel.
        """
        if ctx.author.voice is None:
            return await ctx.send("Not in voice channel")

        vc: wavelink.Player = ctx.voice_client or await ctx.author.voice.channel.connect(cls=wavelink.Player)

        if vc.queue.is_empty and not vc.is_playing():
            await vc.play(search)
        else:
            await vc.queue.put_wait(search)
            await ctx.send(f'Added `{search.title}` to the queue...', delete_after=10)
```

**Comment by slefgameRz** [comment]
> This is within a cog, simply remove the `self` if you are not running this in a cog. I would also recommend joining the discord server for further support.
> 
> ```
>     @commands.command()
>     async def play(self, ctx: commands.Context, *, search: wavelink.YouTubeTrack):
>         """Play a song with the given search query.
> 
>         If not connected, connect to our voice channel.
>         """
>         if ctx.author.voice is None:
>             return await ctx.send("Not in voice channel")
> 
>         vc: wavelink.Player = ctx.voice_client or await ctx.author.voice.channel.connect(cls=wavelink.Player)
> 
>         if vc.queue.is_empty and not vc.is_playing():
>             await vc.play(search)
>         else:
>             await vc.queue.put_wait(search)
>             await ctx.send(f'Added `{search.title}` to the queue...', delete_after=10)
> ```

thank you very much i can fix it now
