### ISSUE TITLE
please help how to fix this 

### ISSUE THREAD

**Issue by slefgameRz** [PythonistaGuild/Wavelink#159]
TypeError: on_wavelink_track_end() missing 1 required positional argument: 'player'

**Comment by jackra1n** [comment]
Github issues are designed for bug reports and feature requests and not a help forum. If you need help using library, please  check out the [documentation](https://wavelink.readthedocs.io/en/latest/), [examples](https://github.com/PythonistaGuild/Wavelink/blob/main/examples/basic_cog.py) or join our discord and ask in a specific channel https://discord.com/invite/ssVqxzqq.
Thanks
