### ISSUE TITLE
Constantly pushing TrackEnd events

### ISSUE THREAD

**Issue by XuaTheGrate** [PythonistaGuild/Wavelink#16]
After calling `stop` once, the player will continue to send TrackEnd for every song that starts via `play`.
[Here](https://mystb.in/ufogeyomey.md) is an example of my logs, showing that running `stop` once will instantly skip the entire queue.
My event hook handler is as simple as 
```python
def event_hook(self, event):
    self.logger.debug("event hook fired %s", event)
    if isinstance(event, wavelink.TrackEnd):
        event.player.next.set()
```
My queue handler un-sets `player.next` and will block until a new song enters the queue. Once it does, it'll play the song and then wait for `player.next` to be set again.
The `event_hook` is instantly firing TrackEnd, which in turn sets `player.next`, and clearing out the entire queue.

**Comment by EvieePy** [comment]
Can't repro but will keep an eye out thanks.

**Comment by EvieePy** [comment]
Still haven’t had any issues with this, and as the websocket was update recently I can assume this bug is gone. Feel free to open another issue if this continues to happen.
