### ISSUE TITLE
Player running endless (without sound)

### ISSUE THREAD

**Issue by Luc1412** [PythonistaGuild/Wavelink#163]
I currently play an MP3 on the lavalink server in a loop. The loop has been accomplished by following code.
```
@commands.Cog.listener(name="on_wavelink_track_end")
    async def _on_track_end(self, player: RadioPlayer, track: wavelink.Track, reason: str):
        if reason != 'FINISHED':
            return
        await player.play(track)
```
This transition works fine so far. I also added `on_wavelink_track_exception` and `on_wavelink_track_stuck` for debug reasons, but both won't get triggered.

I experience that the player randomly stops playing. The client is still connected.
The player got `is_connected()` and `is_playing()` set to True. But when checking the position it got an inappropriate high number set.

My track is about an hour long, but `postion` is set to 21h in seconds.

Pausing and resuming resumes the playback.

**Comment by Hunter87ff** [comment]
exactly the same problem i'm facing!

**Comment by Luc1412** [comment]
@Hunter87ff It seems like this is fixed in Wavelink 2.x. Currently doing a long term test.

**Comment by Hunter87ff** [comment]
Thanks Brother ♥👍

**Comment by Luc1412** [comment]
I let the player run for 2+ days, without any issues. It seems like it's working now reliable. I'll keep the test running and might reopen it, if I encounter the issue again.
