### ISSUE TITLE
Undocumented breaking Player.set_volume change + wrong documentation

### ISSUE THREAD

**Issue by Luc1412** [PythonistaGuild/Wavelink#165]
The recent update to `Player.set_volume` caused a (unintended) breaking change. Instead of setting 1-1000 it's now 0.0 - 5.0 which isn't refelected in the documentation.

This change should be rolled back to Lavalinks native volume implementation as using filters could cause a decrease in performance.

**Comment by Axelancerr** [comment]
This was fixed in 8c1b4d264ad5f15fdd7fabca7a86266a98731896 and a new release on PyPi will be created soon.
