### ISSUE TITLE
Play From Specific Youtube URL

### ISSUE THREAD

**Issue by cwz6h** [PythonistaGuild/Wavelink#169]
How Do I Play From A Specific Youtube URL Instead Of The "search" Argument?

code:
@client.event
async def on_ready():
    client.loop.create_task(node_connect())

@client.event
async def on_wavelink_node_ready(node: wavelink.Node):
    print(f"Node {node.identifier} is ready!")

async def node_connect():
    await client.wait_until_ready()
    await wavelink.NodePool.create_node(bot=client, host='losingtime.dpaste.org', port=2124, password='SleepingOnTrains')

@client.command()
async def play2(ctx:commands.Context, *, search:wavelink.YouTubeTrack):
    if not ctx.voice_client:
        vc: wavelink.Player = await ctx.author.voice.channel.connect(cls=wavelink.Player)
    elif not ctx.author.voice_client:
        return await ctx.reply("Join A VC First!")
    else:
        vc: wavelink.Player = ctx.voice_client
    await vc.play(search)

**Comment by mccoderpy** [comment]
I'm using a RegEx for this.

like for example
```py
import re

URL_REGEX = re.compile(r"(?i)\b((?:https?://|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)+(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'\".,<>?«»“”‘’]))")

# other stuff like connection and co.

@client.command()
async def play(ctx: commands.Context, *, query: str):
    # connecting stuff
    if not URL_REGEX.match(query):
        query = f'ytsearch: {query}' # when it's not a URL then search for it
    tracks = await wavelink.NodePool.get_node().get_tracks(wavelink.YouTubeTrack, query)
    if not tracks: # no tracks found? so return this to the user
        return await ctx.send('No tracks found for {query.repalce("ytsearch: ", ""}')
    else: # track(s) found, so play the first one
        await vc.play(tracks[0])
```

Of curse you can do this in many other ways.

**Comment by chillymosh** [comment]
This is a non issue

**Comment by parker-g** [comment]
anyone know if there's still a way to achieve this with newer versions of wavelink? I'm hosting a lavalink 4.0.0 instance and my wavelink version is 3.2.0

**Comment by chillymosh** [comment]
> anyone know if there's still a way to achieve this with newer versions of wavelink? I'm hosting a lavalink 4.0.0 instance and my wavelink version is 3.2.0

Please do not post in a closed issue for a simple question, this should be asked either on the Discord or in a Github Discussion.
But to answer, just use Playable.search()
