### ISSUE TITLE
AttributeError: 'Player' object has no attribute 'ctx'

### ISSUE THREAD

**Issue by Erush01** [PythonistaGuild/Wavelink#172]
`@commands.Cog.listener()

    async def on_wavelink_track_end(self, player: wavelink.Player, track: wavelink.Track, reason):

        if not self.music_q.is_empty:

            ctx = player.ctx

            vc: player = ctx.voice_client

            msc = self.music_q.pop()

            await ctx.send(embed=nextcord.Embed(title=f"🎶 Now playing: {msc.title}🎶", color=nextcord.Color.blue()))

            await vc.play(msc)`

when i use this code to automatically start the next song in the queue i get this error. What is the fix for this?

> Ignoring exception in on_wavelink_track_end
Traceback (most recent call last):
  File "D:\Yazılım\DiscordBotV2\lib\site-packages\nextcord\client.py", line 445, in _run_event
    await coro(*args, **kwargs)
  File "D:\DiscordBotV2\music2.py", line 52, in on_wavelink_track_end
    ctx = player.ctx
AttributeError: 'Player' object has no attribute 'ctx'

**Comment by chillymosh** [comment]
This is not an issue or bug with the library.
You need to create Player.ctx in the play command.

I can provide better help in the discord.

**Comment by Erush01** [comment]
> This is not an issue or bug with the library. You need to create Player.ctx in the play command.
> 
> I can provide better help in the discord.

it would be great
