### ISSUE TITLE
Wavelink has no attribute 'WavelinkMixin'

### ISSUE THREAD

**Issue by zairullahdev** [PythonistaGuild/Wavelink#176]
Is there alternative to this?
![Screenshot_2022_0722_063252](https://user-images.githubusercontent.com/99532718/180331859-63c93137-f3a2-4459-9c60-9f73c572f8fd.png)

**Comment by IAmTomahawkx** [comment]
Seems like you're out of date. Consider either pinning your wavelink version to a pre-1.0 version (for dpy 1.x) or updating to wavelink 1.x (for dpy 2.0).
