### ISSUE TITLE
Coroutine 'BotBase.load_extension' was never awaited

### ISSUE THREAD

**Issue by ladinzgit** [PythonistaGuild/Wavelink#179]
Hi, it worked well on your personal PC, but it doesn't work with the following error on your hosting PC:

untimeWarning: coroutine 'BotBase.load_extension' was never awaited
  bot.load_extension(f"cogs.{filename[:-3]}")
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

So I want to know what the cause is and how to solve it.

**Comment by chillymosh** [comment]
@ladinzgit this is a discord.py issue and not a Wavelink issue. 
The issue you have though is you did not await load_extension which is a coroutine, as per the error message.
I suggest you join the dpy discord server for further support.
