### ISSUE TITLE
AttributeError: '_MissingSentinel' object has no attribute 'guild'

### ISSUE THREAD

**Issue by Necrosis000** [PythonistaGuild/Wavelink#181]
Hi I am trying to make a setvolume command but I keep getting this error: AttributeError: '_MissingSentinel' object has no attribute 'guild'

Code:
```
@bot.command()
async def setVolume(ctx, *, volume: float):
    vc = ctx.voice_client
    custom_player = CustomPlayer()

    if not vc:
        await ctx.send("I ain't in a vc bro")
    else:
        await custom_player.set_volume(volume=volume)

**Comment by chillymosh** [comment]
Which lib are you using? This usually means you are using ab unsupported fork of dpy or the old 1.7.3.

**Comment by Necrosis000** [comment]
Im using Discord.py 2.0 and wavelink 1.3.3

**Comment by chillymosh** [comment]
Volume is now back to an int in 1.3.3

I suspect it's because of your custom player class. I think you may be misunderstanding how to use the lib.
For further assistance you should join the discord and post more of your code.

**Comment by Necrosis000** [comment]
this is my CustomPlayer

```class CustomPlayer(wavelink.Player):

    def __init__(self):
        super().__init__()
        self.queue = wavelink.queue

**Comment by chillymosh** [comment]
Please join the Discord for further support as this is not a lib issue.

You do not need to make a custom class for this. Player already has a Queue.
