### ISSUE TITLE
player.volume is 0 if you didn't call set_volume

### ISSUE THREAD

**Issue by timelessnesses** [PythonistaGuild/Wavelink#182]
player.volume will always returns 0 instead of actual current lavalink volume if you didn't call set_volume

**Comment by chillymosh** [comment]
Using master I restarted my bot and simply ran the below to get 100 sent back.
This is before using set_volume.
```
    @commands.command()
    async def checkvolume(self, ctx: commands.Context):
        vc: wavelink.Player = ctx.voice_client
        await ctx.send(vc.volume)
```

**Comment by timelessnesses** [comment]
though my side doesn't work?  
```py
vc: wavelink.Player = ctx.voice_client
if volume is None:
    return await ctx.send(
        embed=discord.Embed(
            title="Volume",
            description=f"The volume is currently set to {int(vc.volume)}%.",
            color=discord.Color.green(),
            )
        )
```  
![image](https://user-images.githubusercontent.com/59832159/198196616-750346b0-133e-459a-a029-a907cff97ba0.png)

**Comment by timelessnesses** [comment]
yeah likely my wavelink is old
