### ISSUE TITLE
player.set_volume() stops the song and failes all others in quque

### ISSUE THREAD

**Issue by bestben100** [PythonistaGuild/Wavelink#183]
player.set_volume stops the song and the on_wavelink_track_end(vc: wavelink.Player, track: wavelink.Track, reason): method is called starting with a reoson of 
FINISHED and when it tries to play the next song in quque then ist says LOAD_FAILED

**Comment by chillymosh** [comment]
Please confirm which version Wavelink you are on and whether you are passing a float between 0 and 5.0 or and int of 0 to 1000.

There were changes made between specific versions to accommodate Lavalink changes.
