### ISSUE TITLE
Is there a better way to play a local file?

### ISSUE THREAD

**Issue by Mudpuppy12** [PythonistaGuild/Wavelink#189]
I've finally got playing a local file (to lavalink) from the bot.  (No more ffmpeg)

I'm Just throwing this out here as a general question:

is there a better way to search for a Local Track? I see SearchableTrack, having a return_first=true. Just trying to get my head around the API. Any help is apperciated?

<code>
 @slash_command(name="lplay", description="Play some local music or SFX")
    async def lplay(self, inter: Interaction, search):
        path = "/media/" + search

        search = wavelink.PartialTrack(query=path, cls=wavelink.LocalTrack)

        if inter.user.voice is None:
            return await inter.send(f'You are not connected to any voice channel!')

        # If the bot isn't in a voice channel
        if not inter.guild.voice_client:
            vc: wavelink.Player = await inter.user.voice.channel.connect(cls=wavelink.Player)
        else:
          #See if the bot is in another channel
          if inter.guild.voice_client.channel != inter.user.voice.channel:
            await inter.guild.voice_client.move_to(inter.user.voice.channel) 
            await inter.send(f'Connected to {inter.user.voice.channel}.')
            
        vc: wavelink.Player = inter.guild.voice_client
       
        try: 
           await vc.play(search)
           await inter.send(f'Playing {search.title}')
        except:
           await inter.send(f'{path} Not found!') 
</code>

**Comment by chillymosh** [comment]
You can play a local track using vc.node.get_tracks() providing a full path to the file.
If you want to "search" your local directory for filenames then that's something you'd have to do yourself.

**Comment by Mudpuppy12** [comment]
Thanks chilly,

Got a slightly different take on the above.

<code>
@slash_command(name="lplay", description="Play some local music or SFX")
    async def lplay(self, inter: Interaction, search):
        path = "/media/" + search 
        
        try:   
            search = await wavelink.LocalTrack.search(query=path,return_first=True)
        except:
            return await inter.send(f'{path} Not found!') 

        if inter.user.voice is None:
            return await inter.send(f'You are not connected to any voice channel!')

        # If the bot isn't in a voice channel
        if not inter.guild.voice_client:
            vc: wavelink.Player = await inter.user.voice.channel.connect(cls=wavelink.Player)
        else:
          #See if the bot is in another channel
          if inter.guild.voice_client.channel != inter.user.voice.channel:
            await inter.guild.voice_client.move_to(inter.user.voice.channel) 
            await inter.send(f'Connected to {inter.user.voice.channel}.')
            
        vc: wavelink.Player = inter.guild.voice_client

        await vc.play(search)
        await inter.send(f'Playing {search.title}')
</code>

**Comment by chillymosh** [comment]
@Mudpuppy12 an extremely crude example to play the first found track would be.
Obviously adjust to your needs e.g. return a list of 5 and let user pick from tracks found etc.

```
    @commands.command()
    async def example(self, ctx: commands.Context, search: str):
        d = pathlib.Path("/home/chillymosh/shredbot/music").glob("*.mp3")
        vc: wavelink.Player = ctx.voice_client
        tracks = [s for s in d if search.lower() in s.stem.lower()]
        track = await vc.node.get_tracks(wavelink.LocalTrack, str(tracks[0]))
        await vc.play(track[0])
```

**Comment by Mudpuppy12** [comment]
Awesome. Thank you for the ideas!
