### ISSUE TITLE
How would you stream a mp3 file

### ISSUE THREAD

**Issue by catdogmat** [PythonistaGuild/Wavelink#191]
I have a mp3 file on the internet I want to stream it

**Comment by chillymosh** [comment]
Please join the discord to ask such questions as this is not an issue.
But you would use vc.node.get_tracks(wavelink.Track, url.mp3)

**Comment by catdogmat** [comment]
Thanks So Much

**Comment by catdogmat** [comment]
Im getting the error discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: AttributeError: 'list' object has no attribute 'id'

**Comment by chillymosh** [comment]
@catdogmat again, please join the discord for support questions.
This is basic python, if you look at the type hints or docs you'll see it returns a list of tracks so simply access the first index.
