### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by KRUGSON** [PythonistaGuild/Wavelink#203]
I don't know why but I get this problem everytime when I search a track...

chosen_track = await wavelink.YouTubeTrack.search(query=" ".join(title), return_first=True)
  File "/usr/local/lib/python3.8/dist-packages/wavelink/tracks.py", line 197, in search
    return tracks[0]
IndexError: list index out of range

**Comment by chillymosh** [comment]
@KRUGSON please make sure you are using Lavalink 3.7.4 if you are hosting your own.
Why is query a join? Are you providing it a list of strings?

We would need a bit more information on how your command is structured, what you are typing etc.

You can also join the discord for quicker support.
