### ISSUE TITLE
Loop_all feature doesnt loop currently playing song but rest of Q

### ISSUE THREAD

**Issue by Nowe5** [PythonistaGuild/Wavelink#208]

**Comment by IAmTomahawkx** [comment]
Please provide actionable information in your issue. What is your code? what wavelink version are you using? what os? lavalink version?

**Comment by Nowe5** [comment]
OS: Ubuntu 22.04.2
Wavelink: 2.0.3
Lavalink: 1.3.5
![image](https://user-images.githubusercontent.com/34966090/227715079-b71f4d01-6d8e-4865-bee0-76e52fedcde5.png)

for example 3 added 3 songs in queue. while first one is playing when i activated loop currently playing song is never played again

**Comment by cloudwithax** [comment]
checks out, the codebase has no logic to put the current track into the loop queue. in the meantime, i would recommend adding the currently playing track to the first position in the queue if the loop mode is set to correct this.

**Comment by Nowe5** [comment]
thank you for your suggestion. if its not a bug i am closing the issue. Have a nice day
