### ISSUE TITLE
Cannot connect to host <ssl_host>:443 ssl:default [Name or service not known]

### ISSUE THREAD

**Issue by Hunter87ff** [PythonistaGuild/Wavelink#229]
wavelink version - 1.3.5
python - 3.8.7

```
async def node_connect():
	await bot.wait_until_ready()
	await wavelink.NodePool.create_node(bot=bot,
	                                    host=config.m_host,
	                                    port=443,
	                                    password=config.m_host_psw,
	                                    https=True,
	                                    spotify_client=spotify.SpotifyClient(
	                                     client_id=config.spot_id,
	                                     client_secret=config.spot_secret))
```

**Comment by chillymosh** [comment]
@Hunter87ff Can you not upgrade your Python to at least 3.10 and installed wavelink 2.x and lavalink 3.7.5?

1.x has been outdated for a long time.

**Comment by EvieePy** [comment]
This is for an extremely outdated version of Wavelink.

For these sorts of issues try changing: `localhost` to `127.0.0.1` and vice-versa.
For more help with these issues please consider joining our discord: https://discord.gg/RAKc3HF

As this is not an issue with the library and you have not responded, I will be closing this 👍
