### ISSUE TITLE
Wavelink always using the node from NodePool which is connected first to Nodepool (Ignoring the specs and load of the lavalink server )

### ISSUE THREAD

**Issue by munishkhatri720** [PythonistaGuild/Wavelink#235]
![image](https://github.com/PythonistaGuild/Wavelink/assets/109850452/f24d1eeb-07db-4580-95a7-1f084fd0cbd5)
 
 node : wavelink.Node = wavelink.Node(uri='https://eu-lavalink.lexnet.cc:443',password="lexn3tl@val!nk",secure=True,retries=3,id="LEXNET 1")
 
 is connected first to Nodepool but it is a public node and worst quality (too much load on it )
 but it still playing with this as u can see it is reconnecting again and again 
 
![image](https://github.com/PythonistaGuild/Wavelink/assets/109850452/771b5be5-d9e8-4d20-a521-3dc78287fa3b)

**Comment by munishkhatri720** [comment]
wavelink Nodepool has to rearrange nodes by their loads

**Comment by chillymosh** [comment]
Hi,
The NodePool gets connected to lowest-use Node in the NodePool already. Please make sure you are on the latest version, preferably the git version (2.6.1) as it has some minor fixes.

Do note that the load is determined by how many Players your current Bot has running on it and not what the public node has running on it.
