### ISSUE TITLE
Autoplay also Loop Queue behaving unexpectedly based the docs

### ISSUE THREAD

**Issue by lleans** [PythonistaGuild/Wavelink#238]
- [ ] The autoplay, it reads will handle all skip on queue and auto queue. **auto_queue will be populated if you intially set true on populate**
![image](https://github.com/PythonistaGuild/Wavelink/assets/68429210/0c53eedd-6bee-4fb4-835b-eecca3281c8a)
The problem is, when `autoplay set True`, if you played a song(`with populate False`), then `add song to queue`. It still populate the auto queue. you can fix it by making queue logic itself on `track_end`. It's just confusing

- [ ] The loop property on queue doesn't work as expectedly with currently played song. As it said,

    ![image](https://github.com/PythonistaGuild/Wavelink/assets/68429210/d1b623c6-adff-4878-abad-274a62ea096c)
    
    It do work if you put current played song on first queue, then it will loop that first queue. Sure It do work, but 'ill find it's annoying based the docs. Maybe fix it on next version
    ![image](https://github.com/PythonistaGuild/Wavelink/assets/68429210/ae1a9e87-b652-44e1-ade6-cca4e0e98eae)
    ![image](https://github.com/PythonistaGuild/Wavelink/assets/68429210/18993b20-1dac-4155-a699-b8824fd5de56)

**Comment by chillymosh** [comment]
In Wavelink 2.x this is actually expected behaviour.
There have been discussions to change it to a tribool but there's quite a bit involved.

In 3.x this will most likely be changed.
