### ISSUE TITLE
[Typing] pyright shows `Unknown | SpotifyTrack` as possible yield value for  `SpotifyAsyncIterator.__anext__()`

### ISSUE THREAD

**Issue by Sachaa-Thanasius** [PythonistaGuild/Wavelink#239]
Very minor, but is there any way to type this to be more accurate? Maybe by adding an explicit return type to SpotifyAsyncIterator's `anext()` method?

Wavelink version: 2.6.4
Pyright level: strict

**Comment by Sachaa-Thanasius** [comment]
I'm imagining changing `async def __anext__(self): ...` to `async def __anext__(self) -> SpotifyTrack: ...`, but I'm not sure if it's that simple.

**Comment by chillymosh** [comment]
I believe that would be enough since None is accounted for with calling the `__anext__` dunder again and will raise an exception on exhaustion.

**Comment by Sachaa-Thanasius** [comment]
Seems like all the focus is on Wavelink v3 now, where this isn’t an issue, so I’ll just close this.
