### ISSUE TITLE
nextcord support 

### ISSUE THREAD

**Issue by hellyet** [PythonistaGuild/Wavelink#251]
I've seen previous issues about wavelink & nextcord and i'll have an idea how to add support for nextcord.
I suggest to add import condition: firstly import from discord with "try" block, secondly, excepting ImportError, import from nextcord. I forked this repository localy, but i want to get "official" support for nextcord.

I could add nextcord support in this repository it would be easier to getting featuer from newer versions, instead of updating a fork. 

With nextcord support I will improve a spotify extention.

Can I do this?

**Comment by chillymosh** [comment]
Sorry, we do not support Nextcord, which is why Discord.py is a dependency. It is better maintained library.
We have also dropped the Spotify extension in 3.x 
2.x is EoL and not being updated any further.
