### ISSUE TITLE
track the closure of player wavelink

### ISSUE THREAD

**Issue by llimonix** [PythonistaGuild/Wavelink#275]
when a bot kicks from the voice channel, I need to track this event. In the discord itself, I found a common event disabling bots, people. Even when the bot is moved to another channel and the player is still playing. And I need to track exactly such an event when the bot is kicked or the voice channel is deleted and the player in the lavalink status is deleted

**Comment by chillymosh** [comment]
There are events existing already within discord.py and wavelink.
```
on_wavelink_node_closed
on_wavelink_websocket_closed
on_voice_state_update
```
