### ISSUE TITLE
auto_queue not popularing when running wavelink.Player.play

### ISSUE THREAD

**Issue by Kingi-s** [PythonistaGuild/Wavelink#290]
Hi, in v2.6.3 wavelink.Player.play had a parameter to set populate = True, version 3.0.0 and above doesnt seem to have that.
Previusly the auto_queue would populate when running wavelink.Player.play with parameter populate=True, but now the auto_queue doesnt seem to populate until the player starts actually playing from the auto_queue.

**Comment by EvieePy** [comment]
This was a slight oversight on my part, I have noticed the behaviour myself, I will probably re-add the populate kwarg to player.

**Comment by munishkhatri720** [comment]
Currently, I am manually populating the auto_queue when autoplay mode is set to partial, as Wavelink doesn't populate the auto_queue in partial autoplay mode. However, I want it to only play auto_queue tracks when autoplay mode is set to enabled. Actually, I want to send a drop-down with a track start message for the recommended tracks based on the currently playing tracks, so adding the populate kwarg will be helpful.
