### ISSUE TITLE
Music is not being played for no reason.

### ISSUE THREAD

**Issue by Allowwed** [PythonistaGuild/Wavelink#297]
0|bot  | AutoPlay was unable to continue as you have received too many consecutive errors.Please check the error log on Lavalink.

getitng this in bot console when I play the music WITHautoplay. And the bot spams the songs for autoplay.
No error if autoplay is OFF. The bot shows that it is playing music as I can change it's volume. Which means player.playing return True.
But there is no sound of bot even on 100 volume.
I'm using Wavelink 3.2.0 with Lavalink v4.0.4

**Comment by chillymosh** [comment]
You need to use this hotfix version until there is a new release of Lavalink
https://serux.pro/Lavalink-v4-403-retry.jar

**Comment by Allowwed** [comment]
> You need to use this hotfix version until there is a new release of Lavalink https://serux.pro/Lavalink-v4-403-retry.jar

I'm already using this

**Comment by chillymosh** [comment]
You said you are using 4.0.4, which is not the hotfix version. If you can confirm you are definitely using the hotfix version (You have to move the existing .jar out of the way, rename the new file to Lavalink.jar and restart the service) and it still does not work, then you'll have to raise an issue with Lavalink on their github.

This has no relation to Wavelink.

**Comment by Allowwed** [comment]
> You said you are using 4.0.4, which is not the hotfix version. If you can confirm you are definitely using the hotfix version (You have to move the existing .jar out of the way, rename the new file to Lavalink.jar and restart the service) and it still does not work, then you'll have to raise an issue with Lavalink on their github.
> 
> This has no relation to Wavelink.

https://repo.lavalink.dev/artifacts/lavalink/fe62703c/Lavalink.jar
I'm using this.

**Comment by Allowwed** [comment]
8|lavalink  | 2024-04-08T13:59:04.427Z  WARN 77209 --- [back-1-thread-1] c.s.d.l.s.y.YoutubeAccessTokenTracker    : YouTube auth tokens can't be retrieved because email and password is not set in YoutubeAudioSourceManager, age restricted videos will throw exceptions.


Also getting this in lavalink console

**Comment by chillymosh** [comment]
1. I can't attest for that version you linked, although it is not the version I linked, which you said you was using but proven yet again you are not.
2. I am repeating myself now in that the other error is not related to Wavelink, this is Lavalink related.

**Comment by Allowwed** [comment]
> 1. I can't attest for that version you linked, although it is not the version I linked, which you said you was using but proven yet again you are not.
> 2. I am repeating myself now in that the other error is not related to Wavelink, this is Lavalink related.
> 
> UPDATE: This version does work fine, I just tested it. This is promoted in the Lavalink server.

Okay, just tell me if the bot sends playing message in the on_wavelink_track_start event and deletes the message instantly by calling on_wavelink_track_end event so is that due to lavalink or wavelink? there is only 1 second delay between calling those 2 events where as the track is of 2 minutes

**Comment by chillymosh** [comment]
Without seeing your full code and errors, I can't answer that.
Wavelink does not send any message in track_start / track_end unless you tell it to.

The only reason that track_start and track_end would have events dispatched in such a short period would be due to errors receiving the track from Lavalink, which again would require full logs, or you are exhausting the Queue by performing Queue.get() in the wrong place(s). Especially with AutoPlay mode enabled.

**Comment by Allowwed** [comment]
8|lavalink  | 2024-04-08T15:31:31.972Z TRACE 77209 --- [   XNIO-1 I/O-1] lavalink.server.io.SocketContext         : Sent {"op":"event","type":"TrackEndEvent","guildId":"11170476659898420","track":{"encoded":"QAAA6gMACVdlIFJvbGxpbgAFU2h1YmgAAAAAAAMNQAALcVJdENDYmsAAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1xUkJEejd0Q0NiawEAfmbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9aNTJWdHhCUVpFWjgwYmJfZ1dGb3VuLTUwSDlCQ19oZFJrRXh5UVV6cDNSZHg4T09vUGl6MXRKR3pXRjVXSHd5eWIwazdJT1Q3ZkxNSTd1Rj13MTAwMC1oMTAwMAAAB3lvdXR1YmUAAAAAAAAAAA==","info":{"identifier":"qRBDz7tCCbk","isSeekable":true,"author":"Shubh","length":200000,"isStream":false,"position":0,"title":"We Rollin","uri":"https://www.youtube.com/watch?v=qRBDz7tCCbk","sourceName":"youtube","artworkUrl":"https://lh3.googleusercontent.com/Z52VtxBQZEZ80bb_gWFoun-50H9BC_hdRkExyQUzp3RdxOoPiz1tJGzWF5WHwyyb0k7IOT7fLMI7uF=w1000-h1000","isrc":null},"pluginInfo":{},"userData":{}},"reason":"loadFailed"}



Also got this

**Comment by chillymosh** [comment]
Closing as this is not an issue with the lib. It's YouTube A/B testing related.
