### ISSUE TITLE
An unexpected error occurred while connecting Node

### ISSUE THREAD

**Issue by EliasCouma** [PythonistaGuild/Wavelink#299]
An unexpected error occurred while connecting Node(identifier=, uri=, status=NodeStatus.CONNECTING, players=0) to Lavalink: ""
If this error persists or wavelink is unable to reconnect, please see: https://github.com/PythonistaGuild/Wavelink/issues"

Not 100% sure why this is happening, especially as it's not giving me a specific reason "Lavalink: "" "

**Comment by chillymosh** [comment]
@EliasCouma Please make sure you are running Lavalink 4 - currently you need to use this hotfixed version: https://repo.lavalink.dev/artifacts/lavalink/fe62703c/Lavalink.jar

Also, when trying to connect, make sure the URI has the protocol prefix of `http://`

**Comment by EliasCouma** [comment]
Yeah, sadly still getting the same error

**Comment by chillymosh** [comment]
You'll need to provide some more information. 

- Is Lavalink running?
- What's the application.yaml settings?
- Is the yaml in in the same directory as the .jar?
- Are you calling `java -jar Lavalink.jar` with a terminal inside the actual directory and not outside it?
- If this is all local on the same machine then the yaml can be set to `127.0.0.1` and the URI = `http://127.0.0.1:port`

**Comment by EliasCouma** [comment]
- Yes
- All settings still defaulted, except for the port and address
- Yes
- Yes

**Comment by chillymosh** [comment]
You'll have to show your code, ideally by joining the Discord.
I have a suspicion you are entering a race condition by trying to connect in the wrong event / place.

It either has to be in the Bot subclass `setup_hook` or in the `cog_load` of a Cog of which the extension containing the Cog is loaded within the `setup_hook`

**Comment by EliasCouma** [comment]
You're absolutely right! I moved it into my setup hook and it works now, silly me. Thank you!
