### ISSUE TITLE
LavalinkLoadException with every node

### ISSUE THREAD

**Issue by PowRoyalHighness** [PythonistaGuild/Wavelink#301]
every connection I do gives me the same error and I don't know how to fix it, any idea?

**Comment by chillymosh** [comment]
If you are using public nodes you will have to wait for them to update.

If you are self hosting you will need to make sure you are on 
- Lavalink 4.0.5
- youtube-source plugin
- Using this specific snapshot in your application.yml for lavasrc
```
- dependency: "com.github.topi314.lavasrc:lavasrc-plugin:8096d1a"
      snapshot: true
```

**Comment by PowRoyalHighness** [comment]
I'm using a public nodes list, and the same nodes worked a few days ago, but now they all give me the same error

**Comment by solumath** [comment]
> I'm using a public nodes list, and the same nodes worked a few days ago, but now they all give me the same error

then the server is running old version, thus not related to wavelink

**Comment by chillymosh** [comment]
Update for future reference.

Lavasrc 4.1.0 has now been officially released, negating the need for the snapshot.

If self hosting make sure you specify this in  Lavalink 4.0.5, along with the youtube-source plugin. Remember to disable YouTube in LavaSrc settings.

If using a public node then you need to wait for owner to update.

**Comment by PowRoyalHighness** [comment]
okok, I'll wait for the updates then. Planning on hosting a server myself. Thanks a lot for the help!
