### ISSUE TITLE
An unexpected error occurred while connecting Node

### ISSUE THREAD

**Issue by SKY32K** [PythonistaGuild/Wavelink#320]
(identifier=zceyzKSMD5LDUP_V, uri=https://lavav4.maomy.top:443, status=NodeStatus.CONNECTING, players=0) to Lavalink: "403, message='Invalid response status', url=URL('https://lavav4.maomy.top:443/v4/websocket')" If this error persists or wavelink is unable to reconnect, please see: https://github.com/PythonistaGuild/Wavelink/issues

**Comment by EvieePy** [comment]
403 Status code means forbidden

Which likely means the web-server in front of that Node is rejecting your connection for some reason.

**Comment by SKY32K** [comment]
I have 2 servers and neither can

**Comment by SKY32K** [comment]
I found that it was rejected by CF
