### ISSUE TITLE
Invalid response status on a simple discord music bot

### ISSUE THREAD

**Issue by stevenalegria9** [PythonistaGuild/Wavelink#329]
Hello!

I created a discord bot using the sample code available to try to learn python and have some music with friends. It works perfect for a few days and suddenly, it started having an error message that says: 

`wavelink.websocket: An unexpected error occurred while connecting Node(identifier=WkHYChPAqYVBOECo, uri=https://v4.lavalink.rocks, status=NodeStatus.CONNECTING, players=0) to Lavalink: "433, message='Invalid response status', url='https://v4.lavalink.rocks/v4/websocket'"
If this error persists or wavelink is unable to reconnect, please see: https://github.com/PythonistaGuild/Wavelink/issues`

It gets repeated over and over again and never connects.

I started changing the node uri and password to different ones, tried with and without the "https://" on the uri. Redoing the node portion just in case and doing some research online but the issue persist so I want to ask if someone have encounter this issue before and how to fix it. 

I have installed the discord.py version  2.4.0 and wavelink version 3.4.1

The sample I use as a base is [this one](https://github.com/PythonistaGuild/Wavelink/blob/main/examples/simple.py). I didn't change anything related to the node as it worked when I test it, just added a host and password. [Here it is](https://pastecode.io/s/vk9rz5by) the source code of my project.

I have zero experience on python or programming in general so any suggestion is more than welcome!

**Comment by Blackcool70** [comment]
I've been running my self-hosted bot with wavelink/lavalink music capabilities for a while with no issues whatsoever

are you self-hosting? What is the uri you're using im running mine on "http://localhost:2333"  What does your application.yml look like?

**Comment by chillymosh** [comment]
You are using a public Node, which means you have no control or visibility of its status.

Simply try a different public node or run your own.

**Comment by stevenalegria9** [comment]
> I've been running my self-hosted bot with wavelink/lavalink music capabilities for a while with no issues whatsoever
> 
> are you self-hosting? What is the uri you're using im running mine on "http://localhost:2333" What does your application.yml look like?

Thank you for the response!
I don't have or created an application.yml file but will check that. 
I'm not self-hosting. I took the host from a public lavalink node page. [This one](https://lavalink.darrennathanael.com/) to be precise

**Comment by stevenalegria9** [comment]
> You are using a public Node, which means you have no control or visibility of its status.
> 
> Simply try a different public node or run your own.

Thank you for your response!
I tried a few public nodes and the same issue happens but I'll try to create my own and see how it goes. I'll update this post if it works.

**Comment by stevenalegria9** [comment]
Hello!

So the issue with the original question is fixed. I created an empty lavalink server and it worked! 

Now I have issues trying to adding the plugins for YouTube and Spotify but I think that's for another place.

Thank you for your help!

**Comment by chillymosh** [comment]
@stevenalegria9 The plugins are a simple case of adding a few more lines to the application.yml. 
If you join the Discord, we will gladly assist, as many examples are available.

**Comment by stevenalegria9** [comment]
Thank you for the suggestion!

Joined and found the information I needed. We can consider it fixed now. 

Thank you all!
