### ISSUE TITLE
Wavelink does not support aiohttp 3.6.2, which is required by discord.py 1.2.5

### ISSUE THREAD

**Issue by Yandawl** [PythonistaGuild/Wavelink#38]
When updating discord.py from PyPI:

ERROR: wavelink 0.3.3 has requirement aiohttp<3.6.0,>=3.3.0, but you'll have aiohttp 3.6.2 which is incompatible.

There's some critical garbage collection additions to this release of discord.py so we'd like to update as soon as possible, thank you :)

**Comment by EvieePy** [comment]
Fixed thanks to #39.
