### ISSUE TITLE
example showed in docs always returning "Could not find any songs with that query."

### ISSUE THREAD

**Issue by fghjkgcfxx56u** [PythonistaGuild/Wavelink#77]
while the !connect command worked fine, the "!play test" that should output "10 Hardest Choices Ever (Personality Test) " source: groovy bot always returns "Could not find any songs with that query."
this is from the exact same cog in the example

`@commands.command(aliases=["p"])`
    `async def play(self, ctx, *, query: str):`
        `      tracks = await self.bot.wavelink.get_tracks(f'ytsearch:{query}')`

        `if not tracks:`
            `return await ctx.send('Could not find any songs with that query.')`

        `player = self.bot.wavelink.get_player(ctx.guild.id)`
        `if not player.is_connected:`
            `await ctx.invoke(self.connect_)`

        `await ctx.send(f'Added {str(tracks[0])} to the queue.')`
        `await player.play(tracks[0])`

**Comment by clement-ldr** [comment]
This is a know issue for Lavalink/Lavaplayer : https://github.com/Frederikam/Lavalink/issues/324
