### ISSUE TITLE
Issue with queue command and and music player

### ISSUE THREAD

**Issue by Wasdeq68** [PythonistaGuild/Wavelink#81]
issue is when i react to the bots messages the reactions do nothing and also the queue command the reactions are not removed

**Comment by Cafeepy** [comment]
This doesn't seem to be an issue with the library. For troubleshooting help, maybe you're better off joining the Wavelink Discord server. Please make sure to provide some more details and specifics to help people help you solve your problem.

**Comment by Wasdeq68** [comment]
ok thnx
