### ISSUE TITLE
Nodes and Websocket

### ISSUE THREAD

**Issue by Wasdeq68** [PythonistaGuild/Wavelink#82]
Is it possible to add more nodes and also make it so that the connection to the websocket does not close

**Comment by Cafeepy** [comment]
Yes, additional nodes can be added the same way a single node is added.
If the websocket is closing for no reason, in my experience there's a chance that this is an error with your system. It could be that the system hosting the node doesn't have enough resources and kills Lavalink, or there are network connection issues. I'm not quite sure how to help unless you could provide more details about your problem. Hope this helps!
