### ISSUE TITLE
Music Not Working

### ISSUE THREAD

**Issue by Wasdeq68** [PythonistaGuild/Wavelink#84]
I don't know how to setup a lavalink server on Heroku can someone help me

i dont know how to setup a lavalink server on a vps in general

**Comment by IAmTomahawkx** [comment]
For your first question: you cant run lavalink on herokum

second, 
**Looking to set up a Lavalink server?**
It's pretty simple to do so, and I'll show you here.

**Setup**
Download the latest `Lavalink.jar` from https://github.com/Frederikam/Lavalink/releases here and place an `application.yml` file in the same directory. The file should look like https://github.com/Frederikam/Lavalink/blob/master/LavalinkServer/application.yml.example this.

**Starting it**
Cd into your lavalink directory: e.g `cd <directory>`
Run `java -jar Lavalink.jar`
Check that it started successfully.
*You preferably, should use a process manager for this in the future*

for future reference, please use the pythonista (discord)[https://discord.gg/RAKc3HF] for support, not issues

**Comment by Wasdeq68** [comment]
> For your first question: you cant run lavalink on herokum
> 
> second,
> **Looking to set up a Lavalink server?**
> It's pretty simple to do so, and I'll show you here.
> 
> **Setup**
> Download the latest `Lavalink.jar` from https://github.com/Frederikam/Lavalink/releases here and place an `application.yml` file in the same directory. The file should look like https://github.com/Frederikam/Lavalink/blob/master/LavalinkServer/application.yml.example this.
> 
> **Starting it**
> Cd into your lavalink directory: e.g `cd <directory>`
> Run `java -jar Lavalink.jar`
> Check that it started successfully.
> _You preferably, should use a process manager for this in the future_
> 
> for future reference, please use the pythonista [discord](https://discord.gg/RAKc3HF) for support, not issues

firsty figured out wat i was doing wrong and second u can host a lavalink server on heroku
