### ISSUE TITLE
Request to add loop command

### ISSUE THREAD

**Issue by matrix2113** [PythonistaGuild/Wavelink#89]
The name states it

**Comment by IAmTomahawkx** [comment]
Handling queues and loops is not the library's problem. This is quite an easy thing for users to implement themselves, so i see no reason to add this

**Comment by matrix2113** [comment]
How would I loop it?

**Comment by Cafeepy** [comment]
Assuming you already know how to play a track, all you have to do is wrap that code in the Pythonic loop of your choice and make sure you wait out the rest of the track before playing again. It could look something like this: 
```py
while True:
    await player.play(track)
    await asyncio.sleep(track.duration//1000)
```
While this implementation is rudimentary and probably not what you should use, I think you get the general idea. Hope this helps!

**Comment by matrix2113** [comment]
Ah, seems good. Thanks!
