### ISSUE TITLE
Wavelink 0.9.6 does not support aiohttp 3.7.3

### ISSUE THREAD

**Issue by R4Z3R3X** [PythonistaGuild/Wavelink#92]
Hey, i'm getting an error when installing wavelink for discord.py

ERROR: wavelink 0.9.6 has requirement aiohttp<3.7.0,>=3.6.0, but you'll have aiohttp 3.7.3 which is incompatible.

**Comment by EvieePy** [comment]
Try now.

**Comment by R4Z3R3X** [comment]
The Error is gone!
Thanks for the quick response.
